module.exports = {
  PAGE_LIMIT: 10, // 預設每頁展示10條數據
  NAME_LIMIT: 100, // 限制名稱的字元長度(中文算兩個長度)
  HTTP_METHOD: {
    GET: {
      request_body: false,
      default_tab: 'query',
    },
    POST: {
      request_body: true,
      default_tab: 'body',
    },
    PUT: {
      request_body: true,
      default_tab: 'body',
    },
    DELETE: {
      request_body: true,
      default_tab: 'body',
    },
    HEAD: {
      request_body: false,
      default_tab: 'query',
    },
    OPTIONS: {
      request_body: false,
      default_tab: 'query',
    },
    PATCH: {
      request_body: true,
      default_tab: 'body',
    },
    // http://www.webdav.org/specs/rfc2518.html
    PROPFIND: {
      request_body: true,
      default_tab: 'body',
    },
    PROPPATCH: {
      request_body: true,
      default_tab: 'body',
    },
    MKCOL: {
      request_body: true,
      default_tab: 'body',
    },
    COPY: {
      request_body: true,
      default_tab: 'body',
    },
    MOVE: {
      request_body: true,
      default_tab: 'body',
    },
    LOCK: {
      request_body: true,
      default_tab: 'body',
    },
    UNLOCK: {
      request_body: true,
      default_tab: 'body',
    },
  },
  PROJECT_COLOR: {
    blue: '#2395f1',
    green: '#00a854',
    yellow: '#ffbf00',
    red: '#f56a00',
    pink: '#f5317f',
    cyan: '#00a2ae',
    gray: '#bfbfbf',
    purple: '#7265e6',
  },
  PROJECT_ICON: [
    'code-o',
    'swap',
    'clock-circle-o',
    'unlock',
    'calendar',
    'play-circle-o',
    'file-text',
    'desktop',
    'hdd',
    'appstore-o',
    'line-chart',
    'mail',
    'mobile',
    'notification',
    'picture',
    'poweroff',
    'search',
    'setting',
    'share-alt',
    'shopping-cart',
    'tag-o',
    'video-camera',
    'cloud-o',
    'star-o',
    'environment-o',
    'camera-o',
    'team',
    'customer-service',
    'pay-circle-o',
    'rocket',
    'database',
    'tool',
    'wifi',
    'idcard',
    'medicine-box',
    'coffee',
    'safety',
    'global',
    'api',
    'fork',
    'android-o',
    'apple-o',
  ],
  HTTP_REQUEST_HEADER: [
    'Accept',
    'Accept-Charset',
    'Accept-Encoding',
    'Accept-Language',
    'Accept-Datetime',
    'Authorization',
    'Cache-Control',
    'Connection',
    'Cookie',
    'Content-Disposition',
    'Content-Length',
    'Content-MD5',
    'Content-Type',
    'Date',
    'Expect',
    'From',
    'Host',
    'If-Match',
    'If-Modified-Since',
    'If-None-Match',
    'If-Range',
    'If-Unmodified-Since',
    'Max-Forwards',
    'Origin',
    'Pragma',
    'Proxy-Authorization',
    'Range',
    'Referer',
    'TE',
    'User-Agent',
    'Upgrade',
    'Via',
    'Warning',
    'X-Requested-With',
    'DNT',
    'X-Forwarded-For',
    'X-Forwarded-Host',
    'X-Forwarded-Proto',
    'Front-End-Https',
    'X-Http-Method-Override',
    'X-ATT-DeviceId',
    'X-Wap-Profile',
    'Proxy-Connection',
    'X-UIDH',
    'X-Csrf-Token',
  ],
  METHOD_COLOR: {
    post: {
      bac: '#d2eafb',
      color: '#108ee9',
    },
    get: {
      bac: '#cfefdf',
      color: '#00a854',
    },
    put: {
      bac: '#fff3cf',
      color: '#ffbf00',
    },
    delete: {
      bac: '#fcdbd9',
      color: '#f04134',
    },
    head: {
      bac: '#fff3cf',
      color: '#ffbf00',
    },
    patch: {
      bac: '#fff3cf',
      color: '#ffbf00',
    },
    options: {
      bac: '#fff3cf',
      color: '#ffbf00',
    },
  },
  MOCK_SOURCE: [
    { name: '字串', mock: '@string' },
    { name: '自然數', mock: '@natural' },
    { name: '浮點數', mock: '@float' },
    { name: '字元', mock: '@character' },
    { name: '布爾', mock: '@boolean' },
    { name: 'url', mock: '@url' },
    { name: '域名', mock: '@domain' },
    { name: 'ip地址', mock: '@ip' },
    { name: 'id', mock: '@id' },
    { name: 'guid', mock: '@guid' },
    { name: '目前時間', mock: '@now' },
    { name: '時間戳', mock: '@timestamp' },
    { name: '日期', mock: '@date' },
    { name: '時間', mock: '@time' },
    { name: '日期時間', mock: '@datetime' },
    { name: '圖片連線', mock: '@image' },
    { name: '圖片data', mock: '@imageData' },
    { name: '顏色', mock: '@color' },
    { name: '顏色hex', mock: '@hex' },
    { name: '顏色rgba', mock: '@rgba' },
    { name: '顏色rgb', mock: '@rgb' },
    { name: '顏色hsl', mock: '@hsl' },
    { name: '整數', mock: '@integer' },
    { name: 'email', mock: '@email' },
    { name: '大段文字', mock: '@paragraph' },
    { name: '句子', mock: '@sentence' },
    { name: '單詞', mock: '@word' },
    { name: '大段中文文字', mock: '@cparagraph' },
    { name: '中文標題', mock: '@ctitle' },
    { name: '標題', mock: '@title' },
    { name: '姓名', mock: '@name' },
    { name: '中文姓名', mock: '@cname' },
    { name: '中文姓', mock: '@cfirst' },
    { name: '中文名', mock: '@clast' },
    { name: '英文姓', mock: '@first' },
    { name: '英文名', mock: '@last' },
    { name: '中文句子', mock: '@csentence' },
    { name: '中文詞組', mock: '@cword' },
    { name: '地址', mock: '@region' },
    { name: '省份', mock: '@province' },
    { name: '城市', mock: '@city' },
    { name: '地區', mock: '@county' },
    { name: '轉換為大寫', mock: '@upper' },
    { name: '轉換為小寫', mock: '@lower' },
    { name: '挑選（列舉）', mock: '@pick' },
    { name: '打亂陣列', mock: '@shuffle' },
    { name: '協議', mock: '@protocol' },
  ],
  IP_REGEXP: /^(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])(\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])){3}$/,
  docHref: {
    adv_mock_case: 'https://hellosean1025.github.io/yapi/documents/mock.html',
    adv_mock_script:
      'https://hellosean1025.github.io/yapi/documents/adv_mock.html',
  },
}
